language: ruby
rvm:
- 2.0.0
- 2.1.2
deploy:
  provider: rubygems
  api_key:
    secure: d3hZ59WTiKS88F921Nol2unTq0NiJQvlCks6qCb+pteFFsd5NHRIvHjVMwtjsSrl2/UddeXT8+pehAdzEycnGRG2vfyhIIyDcLDGLRSJgjl2TxhDxKl31bBhDn5d4oB6fYaS+cCBe7DYYcbdova/QkvKxmibTziDpMwbStdR9EA=
  gem: blinkbox-common_mapping
  on:
    repo: blinkboxbooks/common_mapping.rb
    rvm: 2.1.2
    branch: master
